#pragma config(Motor,  motorA,          leftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          rightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is used for the initial calibration. It was initially thought that this would be used in more instances
//This was not the case, but there's no sense in removing it now.
#define COLOR_SENSOR_AVERAGE_BUFFER_LEN 10
#define SONAR_SENSOR_AVERAGE_BUFFER_LEN 10

//The weight of new values when following a line. A higher weight allows for more precise line following.
#define MOVING_AVG_WEIGHT 75.0

//Needed a middling weight for reacquiring lines. This turned out to be a good weight.
#define REAQ_MVG_WEIGHT 45.0


//the ratio will change over time
int myRatio = 5;
//Array of turning ratios
int myRatioArray[11] = {
	-35,
	-30,
	-20,
	-15,
	-10,
	0,
	10,
	15,
	20,
	30,
	35
};

void moveForward();
task moveBot();
void getNewRatio();

task main()
{
	startTask(moveBot);

	while (true){};
}

//start with biased random walk
task moveBot() {
	// Choose new direction
	moveForward();
}

/*
move forward based on the random ratio generated
*/
void moveForward() {
	// Infinitely choose new ratio of turn and go for 100ms
	while (true) {
		getNewRatio();
		wait1Msec(800);
	}
}

/*
Bayesian Network implementation of biased random walk.
Chooses a new ratio of turn with probability directly
linked to current ratio of turn.
*/
void getNewRatio() {
	int i=0, j, k;
	//Creates array 0-9 that will be filled with
	// possible ratios. Represents percent chance.
	int arr[10];
	// Fills part of array with probability of going
	// one index less on myRatioArray
	for (j = 0; j < myRatio; j++) {
		arr[i++] = myRatio - 1;
	}
	// Fills part of array with probability of going
	// one index more on myRatioArray
	for (k = myRatio; k < 10; k++) {
		arr[i++] = myRatio + 1;
	}
	int randomInt = random(9);
	int selection = arr[randomInt];
	if (selection == 0 || selection == 10) {
		myRatio = 5;
	} else
		myRatio = selection;
	setMotorSync(leftM,rightM,myRatioArray[selection],35);
}
